language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
script: ./run_tests.sh
install:
        pip install -r requirements.txt -r test_requirements.txt
notifications:
  email:
    - jason.louard.ward@gmail.com
